{% set version = "1.7-12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-energy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/energy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/energy/energy_{{ version }}.tar.gz
  sha256: ac2224befa4c6ab62f99816ff670b1ee35288cabb7db362257e9af21c87e6f72

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-boot                       # [build_platform != target_platform]
    - r-gsl                        # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.6
    - r-boot
    - r-gsl
  run:
    - r-base
    - r-rcpp >=0.12.6
    - r-boot
    - r-gsl

test:
  commands:
    - $R -e "library('energy')"           # [not win]
    - "\"%R%\" -e \"library('energy')\""  # [win]

about:
  home: https://github.com/mariarizzo/energy
  license: GPL-2.0-or-later
  summary: E-statistics (energy) tests and statistics for multivariate and univariate inference, including distance correlation, one-sample, two-sample, and multi-sample tests for comparing multivariate distributions, are implemented. Measuring and testing multivariate independence based on distance correlation, partial
    distance correlation, multivariate goodness-of-fit tests, k-groups and hierarchical clustering based on energy  distance, testing for multivariate normality, distance components (disco) for non-parametric  analysis of structured data, and other energy statistics/methods are implemented.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
