{% set version = '1.7-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-energy
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/energy_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/energy/energy_{{ version }}.tar.gz
  sha256: 24c2cf080939f8f56cd9cda06d2dfc30d0389cd3ec7250af4f9a09a4c06b6996

build:
  merge_build_host: True  # [win]
  number: 1002
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.6
    - r-boot
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.6
    - r-boot

test:
  commands:
    - $R -e "library('energy')"           # [not win]
    - "\"%R%\" -e \"library('energy')\""  # [win]

about:
  home: https://github.com/mariarizzo/energy
  license: GPL (>= 2)
  summary: E-statistics (energy) tests and statistics for multivariate and univariate inference,
    including distance correlation, one-sample, two-sample, and multi-sample tests for
    comparing multivariate distributions, are implemented. Measuring and testing multivariate
    independence based on distance correlation, partial distance correlation, multivariate
    goodness-of-fit tests, k-groups and hierarchical clustering based on energy distance,
    testing for multivariate normality, distance components (disco) for non-parametric analysis
    of structured data, and other energy statistics/methods are implemented.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
