travis:
  secure:
    BINSTAR_TOKEN: jZt1DWtOXf1JkeSfU3KWrPvmwEFd2xAGaqslkTU74fhbYKyRuvxvYCO2PiX+nl0Qr1LEz9S43vxn01v5QakjxvVHQpxLe/tIOtfb8g84QXyFFgECLktRNNiaPJ2ve2isPwXRS2B7mTszdKWye0vxa3UIN9uEnQiHJ2SQaOcUStkTqGCTipVWvN4TGsihgM6hGzp5rhuZ2sS43YCKkZ82onmxv8dqCBAqnhtHYIT7n5QejkJmJLwTAO5h08kbiR9rjKUC9iinMlQMS+nT3Wq9Sa1slR0cjd62gx/pW8EZwcEE8fGakCZe2+aOXn1s5YMU+5Rh8GrP8UwBmNJcVwSjp9pnkDd2R+eIBiaVsSiW4MpUA+kGGd7uGwW3FPPANlriJ4wn5IWQu7D4YubhKTDSAG1ZF9VGeS724LpqK3ngajfpVg4OMqX8oGlsHAvdH8GFiAr4ZW06vRqlm7pxNpd5a11Ni2LAbPVGBbgVji4ibO8GY9YvZHnCkCpHuc+4N52064OFVHjxWcuxQS7Q3A3o+GOQJB5tN8T9BlKR2/TlDECu7DD6oqmiWsFrfUu6UbcCQdiqGy7s6X6GxH8Ia+o1ultNMUzg6G3fN+C5+KmCMMTRpHSx5Wk3AbZurl+A8igJ+CR/zn7+oaT3mBbcuYTbcTPhNA1OABls7jViYfIwAc4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
