travis:
  secure:
    BINSTAR_TOKEN: oXDbEU+eY90dd+9eIVWzxMDYF/CDdSBnMKfUDMHJtp6N2v2b1yKn2pWwYIDX/xznSCRzxaV9sPjoCy0m5iTAWvCI/FbXBSHzo4eTWWMrxchWxBwwa4o86bTbi2F2z2fCZv/VX5xTbuq2+3jTbCn4emVADGucqSbNcxn64AcVKqyGhqQ7l2rf6WK++9mfS/2UDGA/46dwF4NT56TVdiNB/htnXUarJImB9WuVAQMX3/Vkx9wboiXy5gVTMMihv3V3IvNM1/XM3orvd3zo+CtgluJKPPA/UELgokRDvmIY6RNYz1QyhYSgTlP+b8zjWxuRFhF3aYdr8KI0xnoBhE9V2442Hcm8Y7fjRx4ULE7FuVHkViUTFDPRfgjA1VWLGehViCyh1GpKfQtE9SIX81R2j6O+31hhxciyCmqU30znNMYchvKTrBFmo1AG8fQ6NLVlHu24t2LLC4ZKvoHT7FROds1fNT6PysKZj9ZdtgjX9oHQ/rjm5we+gt+6CXZ8fkHt0+sd672a3jMvHb+ttdjnFA1Kz3PhEhQa9yCYvObfPVWw8GNj9zUPD6bSiI2ifUVYg7xsAmqoKMVAV94mC06blI2sKH51hzAW2RbGomIqWQwz2W4sohk6zGkCa2lsicgV9ugMsPgylfOHwpFW69bS/3ElNk6pCOsCwNDiwunLDEU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
