travis:
  secure:
    BINSTAR_TOKEN: XyFBwfpZW6oqVgHsNJZgEsyNF7pkkwAFRflgCV9KqXl7pyw27GBLn4alshqa2iljBWYwZFz6FcVH+LVw65Y1usCupZ9EiJKQ4Y8z3MXtHXv3/YJYJT0UAqLuUcQM7Fw94WNMxdgZtH5+5PNkXkAqiXq5I1mN9gqgzxnS5AvUDWDvmPgYX28f49y8KMW5AwFY9bVTAj52zHGizmrnnl2gKrOJWq38xJ2ZAe63yw+mm6lbl4YWllx/oydBva9wqQI+t8JtE9bgRvfGeKoXJcD0lMgk6Z3RtRinUD3jmZshInBgToWSKto/gCmAzJmwsTY1PIcRKjTPdNaAdiUDOEx4Yhrvpuf3aNiNemb5n0lHwxzspQYcP3jiYR6LjgzshY0aoAPlnXvu0edkgu9JWmZV8qTQjQYsebChI193Mk+AsRDz/z3OUVxfxF4r3ohzPBLVtqKsQRu2D8rI/nVJ87wzIG/PBrQIYOFgE1ew67RgY7RyD1cJgfV5FC8Obq12KJhf2mqMMsoe4ljOO3y+CFIo5psxSL/3SKBsIZuCHgutHH3VGEynFOPDkckO+Akxf9TNFdEieJLerqjG9yb8nlqo+Vw8nGdXbm8AB4VeN9AHVQ1c245pCzBfbd1j8IMrnNX4W+P/oaVhs2CK+ypiMaP76wu3EnGCgb/O/aeYhSi6VRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
